### ISSUE TITLE
Setting up DNA parser issue

### ISSUE THREAD

**Issue by nate97** [open-toontown/open-toontown#10]
Hello, I had attempted to get this project up and running the other day, and though I *was* able to get the server's started, the client logged in, to the pick-a-toon screen, and sucessfully create a toon, I was unable to get this software to be capable of parsing DNA files without modifying it (pdna files specifically), I was wondering if I could get some information on this?

I think this is a fantastic project, and once I get it up and running, would love to help out where I can. Thank you.

**Comment by jwcotejr** [comment]
Provided you are using the `feature/cxx-parser` branch of libpandadna, you should be able to run the client & server with just the raw DNA files.

**Comment by nate97** [comment]
Thank you for the information, could I ask, do I simply need to compile the DNA parser with something such as cmake? & if so, after that would be completed, how would I point opentoontown to use the compiled libraries? Thanks

**Comment by jwcotejr** [comment]
You should build https://github.com/open-toontown/libpandadna/tree/feature/cxx-parser using CMake, then place the `libpandadna` binary (which will be a `.pyd` file on Windows, and a `.so` file on macOS/Linux) in the root directory of https://github.com/open-toontown/open-toontown. It will then be imported when you run Open Toontown.
