### ISSUE TITLE
Client crash when entering Toon Hall

### ISSUE THREAD

**Issue by RenegadeActual** [open-toontown/open-toontown#103]
When trying to continue post-tutorial quest to talk to Pete; game client crashes when entering Toon Hall.
![image](https://github.com/open-toontown/open-toontown/assets/53503727/f00b627f-d360-421b-92b4-23fd403dbe40)
Seems like some kind of positioning error - I am not savvy enough in Python to figure out the problem.

**Comment by DarthMDev** [comment]
Seems like an easy fix , seems to be a missing import
