### ISSUE TITLE
Removal of gender

### ISSUE THREAD

**Issue by DarthMDev** [open-toontown/open-toontown#116]
Wondering if it would be in-scope for this project to remove gender to be inclusive. If so i might start working on a pull request to implement this

**Comment by DarthMDev** [comment]
@LittleToonCat

**Comment by DarthMDev** [comment]
Bump

**Comment by badcodecat** [comment]
What were the original reasons for closing and could this be reopened?
Several of my friends could benefit from this.

**Comment by DarthMDev** [comment]
> What were the original reasons for closing and could this be reopened? Several of my friends could benefit from this.

https://github.com/open-toontown/open-toontown/pull/120#issuecomment-1837829060
