### ISSUE TITLE
Changing News, Whitelist, and other Internet based things to be Local

### ISSUE THREAD

**Issue by ghost** [open-toontown/open-toontown#12]
So, as it is right now, The Whitelist, News, and maybe other parts of the game, pull data from Disney's old servers.

While this is fine for now, it might be best to get said data, add it to this repo, and then change the code to read the files locally, so that way, the data will not be lost to time, should the Disney servers for said data ever go down.

**Comment by ghost** [comment]
I've also been informed that some signs on the street also need internet? Might need to look into that, as well.

**Comment by Bob-by** [comment]
> I've also been informed that some signs on the street also need internet? Might need to look into that, as well.

That can be fixed in \toontown\hood\StreetSign.py copy and paste this code line 12
"    StreetSignFileName = config.GetString('street-sign-filename', 'texture.jpg')" (without " of course=
NOTE: the street sign needs to be downloaded already for it to apply

**Comment by jwcotejr** [comment]
These will eventually be loaded from the resources by default with an option to download them over the internet as well that won't be enabled by default.
