### ISSUE TITLE
Open Toontown development stream VODs?

### ISSUE THREAD

**Issue by irradiatory** [open-toontown/open-toontown#15]
This is one of those issues where i have to say that this issue is only here because i've yet to find any other way to contact the person(s) involved!

It seems that the "Sparky Rewritten" Youtube channel no longer exists! It seems the Open Toontown dev streams were uploaded there. And, according to hearsay, although i'm not sure myself, other similarly informational toontown-related content was hosted there.

Perhaps it was deleted by Youtube administration? I cannot say, but it would be very nice to have a resource to at least know how to get a local copy of this thing up and running, if nothing else. Perhaps the videos are mirrored somewhere else? Or perhaps someone here can give an executive summary....

**Comment by kris-diaz** [comment]
Alright, I'm probably gonna miss some stuff, as I haven't set up a server a few months.  

So first things first, you need a Linux build, either in a VM or on a computer.  After setting up a Linux system, such as Ubuntu or Debian, update the system.  Do this by opening the terminal and typing;

`sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade`

This updates the machine if its out of date.  Also, you should be familiar with sudo commands, which are like doing a command as admin.  Anyways, you will need to clone some things from github.  First, make sure git is installed with `sudo apt-get install git`.  Then, clone all open-toontown repositories.  To do this, type in the terminal `git clone "Github url"`.  An example is `https://github.com/open-toontown/panda3d.git` to clone the Panda3D repository, which is the first repo to clone.  

After cloning Panda3D, change your directory to the Panda3D folder with `cd Panda3D`.  Then, you must download all Panda3D dependencies, via this command `sudo apt-get install build-essential pkg-config fakeroot python-dev libpng-dev libjpeg-dev libtiff-dev zlib1g-dev libssl-dev libx11-dev libgl1-mesa-dev libxrandr-dev libxxf86dga-dev libxcursor-dev bison flex libfreetype6-dev libvorbis-dev libeigen3-dev libopenal-dev libode-dev libbullet-dev nvidia-cg-toolkit libgtk2.0-dev libassimp-dev libopenexr-dev`.  Its a really long command, but it should install all the things you need to build Panda3D.  Afterwards, build Panda3D with this command `python3 makepanda/makepanda.py --everything --installer --no-egl --no-gles --no-gles2 --no-opencv`.  This will build Panda3D on your system, which may take awhile.  After its done, unpack the Panda3D package with `sudo dpkg -i panda3d*.deb`. 

You should now have Panda3D installed.  To check if Panda3D is installed correctly, use a python program or terminal command to test it.  For example, type python3 in the terminal.  Then type and enter after each line: `from direct.showbase.ShowBase import ShowBase` `ShowBase()` `run()`  This will open a Panda3D window, which will be grey if no errors are thrown, Panda3D is installed correctly.  

Part 1 of ???: Ill start up my server and post the guide for getting the other repos up and working (such as libpandadna and Astron).  Make sure to clone the other open-toontown repositories, especially libpandadna, Astron, open-toontown, and resources.

**Comment by irradiatory** [comment]
Thanks for that. I've actually gotten that far already, as i'm running ubuntu already and have compiled panda3d and astron successfully.

I've actually got the game to produce a window, but once it shows a short "loading" animation (with the toontown logo), it just gets stuck on a grey screen. If it helps anyone, the output looks something like this (after running `python3 -m toontown.toonbase.ToontownStart` from the root of `open-toontown`):

<details>
<summary>toontownD-200514_001252.log</summary>

```
Starting Toontown...
Current time: May 14 00:12:52 2020
sys.path =  ['', '/home/irradiatory/clone/open-toontown', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/irradiatory/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages', '/usr/share/panda3d']
sys.argv =  ['/home/irradiatory/clone/open-toontown/toontown/toonbase/ToontownStart.py']
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
setRegistry[EXIT_PAGE] = normal
ToontownStart: Polling for game2 to finish...
ToontownStart: Game2 is finished.
ToontownStart: Starting the game.
ToontownStart: setting default font
:05-14-2020 00:12:53 ToonBase: Default graphics pipe is glxGraphicsPipe (OpenGL).
:05-14-2020 00:12:53 ToonBase: Successfully opened window of type glxGraphicsWindow (OpenGL)
:05-14-2020 00:12:53 ShowBase: __dev__ == False
ToontownStart: Loading default gui sounds
ToontownStart: serverVersion:  sv1.0.47.38
:05-14-2020 00:12:53 Loader: starting bulk load of block 'init'
TTAccount: accountServer from launcher:
TTAccount: default accountServer:  https://toontown.go.com
AppRunner has been removed and AppRunnerGlobal has been deprecated
:05-14-2020 00:12:54 OTPClientRepository: Using connect method 'http'
:05-14-2020 00:12:54 OTPClientRepository: loginInterface: LoginAstronAccount
:05-14-2020 00:12:54 Loader: At end of block 'init', expected 138, loaded 4, duration=0.9905660000000001
:05-14-2020 00:12:54 OTPClientRepository: Connecting to gameserver directly (no proxy).
:05-14-2020 00:12:54 OTPClientRepository: Connecting to //127.0.0.1:7198 via HTTP interface.
:05-14-2020 00:12:54 OTPClientRepository: Successfully connected to //127.0.0.1:7198.
:05-14-2020 00:12:59 ToonBase: User closed main window.
:05-14-2020 00:12:59 OTPClientRepository: Sent disconnect message to server
:05-14-2020 00:12:59 OTPClientRepository: Closing connection to server.
:05-14-2020 00:12:59 OTPClientRepository: Exiting cleanly
:05-14-2020 00:12:59 ToonBase: Exiting Toontown: errorCode = None
```

</details>

I've been trying to look through the source code to find out where everything is stopping, but there is a lot of code and frankly i don't know the structure of it !

**Comment by kris-diaz** [comment]
Yeah, you have to have Astron running, then the Uberdog and AI servers running before you can connect the client.  You also need Libpandadna to parse DNA files (DNA files are streets and playgrounds).  I'll post the full guide later today as I'm building Panda3D on a VM right now, but it isn't too hard after building Panda3D.

**Comment by kris-diaz** [comment]
Also if you want to make some progress before then, you can run the AI and Uberdog servers to try to get the login screen.  I think its `python3 -m toontown.uberdog.UDStart` and `python3 -m toontown.ai.AIStart`.  You run these 2 after running Astron, and then run the ToontownStart file.  It should connect to the server and go to the login screen, but I don't think you'll get too far without Libpandadna built.  

Also, the youtube channel only had dev streams related to Open Toontown.  I think there was about 10 or so, with the last one not being uploaded as it wasn't really related (there was some inappropriate stuff shown by accident.)  It's a shame they are no longer available, as I had to constantly go back to them to get the server fully working.

**Comment by irradiatory** [comment]
Ok, that's very useful. I read about the OTP/Astron architecture so i have an idea how it works, but i didn't realize you had to do those particular things....

With a few very hacky hacks modifying the `CMakeLists.txt` and `run_interrogate.py`, i was able to compile libpandadna. But if i put the `libpandadna/build` directory in my `$PYTHONPATH` and then `import libpandadna` all i get is `NameError: name 'std::ostream' is not defined`.... so clearly i'm missing something or just don't understand how shared object files interact w/ python 3

**Comment by kris-diaz** [comment]
If you got libpandadna working, I think you are supposed to get the libpandadna.so file created by cmake and paste it into the open-toontown directory.

**Comment by irradiatory** [comment]
Ok, i copied `libpandadna.so` into the root dir of `open-toontown` and tried those commands. Unfortunately i think the problem persists (with `import libpandadna` ultimately failing) because when i run `python3 -m toontown.ai.AIStart`, i get:

<details>
<summary>end of `python3 -m toontown.ai.AIStart` output</summary>

```python
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "open-toontown/toontown/ai/AIStart.py", line 33, in <module>
    simbase.air.connect(host, port)
  File "/usr/share/panda3d/direct/distributed/AstronInternalRepository.py", line 602, in connect
    failureArgs=[host, port])
  File "/usr/share/panda3d/direct/distributed/ConnectionRepository.py", line 509, in connect
    successCallback(*successArgs)
  File "/usr/share/panda3d/direct/distributed/AstronInternalRepository.py", line 620, in __connected
    self.handleConnected()
  File "open-toontown/toontown/ai/ToontownAIRepository.py", line 111, in handleConnected
    self.createZones()
  File "open-toontown/toontown/ai/ToontownAIRepository.py", line 222, in createZones
    self.generateHood(DDHoodDataAI, ToontownGlobals.DonaldsDock)
  File "open-toontown/toontown/ai/ToontownAIRepository.py", line 203, in generateHood
    self.dnaDataMap[zoneId] = loadDNAFileAI(self.dnaStoreMap[zoneId], self.genDNAFileName(zoneId))
NameError: name 'loadDNAFileAI' is not defined
```

</details>

**Comment by kris-diaz** [comment]
Are you using the develop branch of open-toontown?  I had a similar problem with libpandadna, but I don't recall how I fixed it.  I think I might have deleted a few imports in OTP that were giving a libpandadna import error, I just don't know exactly what I did. I have a fully working server on one of my PCs, I just have to find it and see what I did.

**Comment by irradiatory** [comment]
```bash
[open-toontown/] $ git branch --list
* develop

[libpandadna/] $ git branch --list
* master
```

just trying to import libpandadna inside of an ordinary python 3 shell is a non-starter:

<details>
<summary>import libpandadna</summary>

```bash
[open-toontown/] $ python3
Python 3.6.9 (default)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libpandadna
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'std::ostream' is not defined
```

</details>

so i must have compiled it wrong. If you;re curious what hacks i tried:

<details>
<summary>libpandadna hacks</summary>

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 93e7c02..36e2a68 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -20,9 +20,10 @@ endif()
 ### Panda3D dir ###
 if (APPLE)
     SET(PANDA_DIR "/Developer/Panda3D" CACHE STRING "Panda3D directory.")
-endif()
-if (WIN32)
+elseif (WIN32)
     SET(PANDA_DIR "C:\\Panda3D-1.10.0" CACHE STRING "Panda3D directory.")
+elseif (UNIX)
+    SET(PANDA_DIR "/usr" CACHE STRING "Panda3D directory.")
 endif()
 SET(BUILD_STATIC_LIB OFF CACHE BOOL "If true, will build a static lib")
 execute_process(COMMAND ${PYTHON2_EXECUTABLE} "${CMAKE_SOURCE_DIR}/src/run_interrogate.py" "${PANDA_DIR}")
@@ -103,9 +104,11 @@ include_directories(src/base)
 include_directories(src/suit)
 include_directories(src/components)
 include_directories(${PANDA_DIR}/include)
+include_directories(${PANDA_DIR}/include/panda3d)
 include_directories(${PYTHON_INCLUDE_DIR})
 include_directories(/usr/include/eigen3)
 link_directories(${PANDA_DIR}/lib)
+link_directories(/usr/lib/x86_64-linux-gnu/panda3d)

 set(LIBPFX "")
 if(WIN32)
@@ -139,6 +142,7 @@ if (NOT BUILD_STATIC_LIB)
     # Add p3interrogatedb, if it exists
     find_library(HAVE_P3INTERROGATEDB
                  ${LIBPFX}p3interrogatedb
+                 PATHS /usr/lib/x86_64-linux-gnu/panda3d
                  HINTS ${PANDA_DIR}/lib)

     if (HAVE_P3INTERROGATEDB)
@@ -151,6 +155,7 @@ if (NOT BUILD_STATIC_LIB)
     # Add p3pandatoolbase, if it exists
     find_library(HAVE_P3PANDATOOLBASE
                  ${LIBPFX}p3pandatoolbase
+                 PATHS /usr/lib/x86_64-linux-gnu/panda3d
                  HINTS ${PANDA_DIR}/lib)

     if (HAVE_P3PANDATOOLBASE)

diff --git a/src/run_interrogate.py b/src/run_interrogate.py
index e8ee9a3..c2a98dc 100644
--- a/src/run_interrogate.py
+++ b/src/run_interrogate.py
@@ -18,12 +18,12 @@ def run_command(cmd):
 def interrogate(module):
     print 'Interrogating', module
     cmd = os.path.join(pandadir, 'bin', 'interrogate')
-    cmd += ' -D__inline -DCPPPARSER -DP3_INTERROGATE=1 -D__cplusplus -fnames -string -refcount -assert'
-    cmd += ' -S %(pandadir)s/include/parser-inc -S %(pandadir)s/include -I %(pandadir)s/include -I%(srcdir)s/base -I%(srcdir)s/suit -I%(srcdir)s/components'
+    cmd += ' -D__inline -DCPPPARSER -DP3_INTERROGATE=1 -D__cplusplus=201103L -fnames -string -refcount -assert'
+    cmd += ' -S %(pandadir)s/include%(linux)s/parser-inc -S %(pandadir)s/include%(linux)s -I %(pandadir)s/include%(linux)s -I%(srcdir)s/base -I%(srcdir)s/suit -I%(srcdir)s/components'
     cmd += ' -srcdir %(srcdir)s/%(module)s -oc %(srcdir)s/%(module)s_igate.cxx -od %(srcdir)s/%(module)s.in -python-native -DCPPPARSER -D__STDC__=1'
-    cmd += ' -D__cplusplus -D__inline -longlong __int64 -D_X86_ -DWIN32_VC -DWIN32 -module libpandadna -library %(module)s -Dvolatile='
+    cmd += ' -D__inline -longlong __int64 -D_X86_ %(win32)s -module libpandadna -library %(module)s -Dvolatile='

-    cmd = cmd % {'pandadir': pandadir, 'module': module, 'srcdir': srcdir}
+    cmd = cmd % {'pandadir': pandadir, 'module': module, 'srcdir': srcdir, 'linux': '/panda3d' if 'linux' in sys.platform else '', 'win32': '-DWIN32_VC -DWIN32' if sys.platform == 'win32' else ''}
     files = glob.glob(os.path.join(srcdir, module, '*.h'))
     for file in files:
         cmd += ' %s' % os.path.basename(file)
```

</details>

**Comment by ComradeNapCali** [comment]
@irradiatory You need to import panda3d.core before you can import libpandadna. I should also add that you need to switch to the "feature/cxx-parser" branch, as that is required.
As for the VODs, during a voice chat I was in, John said that he had to delete his channel because of Disney NDAs. (He was doing the Disney College Program, so it's understandable.)

**Comment by irradiatory** [comment]
Thank you! Switching to the `feature/cxx-parser` branch did the trick, although i did have to make one other change -- besides the diffs i listed earlier under "libpandadna hacks". If you compile with GCC *or* with Clang, you will get something like:

```
../src/base/DNAStorage.cxx:512:24: error: non-const lvalue reference to type '__normal_iterator<...>' cannot bind to a temporary of type '__normal_iterator<...>'
            for (auto& it = m_suit_edges[index].begin(); it != m_suit_edges[index].end(); ++it)
                       ^    ~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Which is apparently just a simple C++ programming error which can be fixed by changing that `auto&` to an `auto`, thus no longer implicitly asking to hold a reference to a temporary rvalue(!)

With that, it seems that cog DOs are being spawned and removed as you would expect, although to be honest i wasnt sure what to expect from the `stdout`/`stderr` output of these programs. <del>Although if i try to launch the game i do just end up with `AstronLoginManagerUD(warning): Unable to associate user dev with account 100000000!`, so i will have to figure out how to authenticate....</del> EDIT: nevermind it created the account for you when you attempt to login with a dev account, so i just had to try again haha
