### ISSUE TITLE
Replace everything with anesidora 

### ISSUE THREAD

**Issue by DarthMDev** [open-toontown/open-toontown#17]
Now that we anesidora shouldn’t we replace the server files with anesidora server files?

**Comment by DarthMDev** [comment]
Probably going work on a pr to do this

**Comment by ComradeNapCali** [comment]
An argument could be made that Open Toontown is a clean room project. Adding the server code from Anesidora would break that vision. It would make more sense to fork this project, then add Anesidora code.

**Comment by DarthMDev** [comment]
> An argument could be made that Open Toontown is a clean room project. Adding the server code from Anesidora would break that vision. It would make more sense to fork this project, then add Anesidora code.

You make a good point I will close this
