### ISSUE TITLE
Suggestion: FMOD Audio Support

### ISSUE THREAD

**Issue by ghost** [open-toontown/open-toontown#29]
If possible, I think it would be nice to have FMOD as an optional audio engine, for a few reasons.

First reason is MIDI support. If one wanted to continue using MIDI in the game, I think this would be a nice option to have.

Secondly is in relation to looping audio. In other game engines with FMOD support, its possible to set something called loop points, which tells the engine to loop a specific part of an audio file, which is much more flexible than the end to end playback Open AL uses. If FMOD in Panda also supports this, then I think it would be a great option to have.

**Comment by jwcotejr** [comment]
Hi there,

Open Toontown is able to make use of FMOD audio, simply by changing `audio-library-name p3openal_audio` to `audio-library-name p3fmod_audio` in Configrc.prc.

Keep in mind that your build of the Panda3D SDK will need to have been built with support for FMOD audio. In the case of the Panda3D SDKs for Windows & macOS that we provide, FMOD audio support is built into Panda3D.

Take care,
John

**Comment by ghost** [comment]
Hey John,

Thanks for letting me know! I wasn't aware FMOD support was already included in the build of Panda provided. Would you happen to know where I could find the latest documentation for using FMOD within Panda? I ask, so I can see all it supports, and how to use the features it can do.

**Comment by jwcotejr** [comment]
There's the general sound documentation for Panda3D, which can be found here: https://docs.panda3d.org/1.10/python/programming/audio/index

Some features that are exclusive to FMOD are covered there, though I'm not certain that the documentation is entirely up-to-date with the engine or not.

It's worth noting that, at the moment, Panda3D is using a bit of an older version of the FMOD audio library, so it lacks some of the capabilities of the newer versions of FMOD. Some progress has been made with updating FMOD in Panda3D (https://github.com/panda3d/panda3d/pull/1032), though it is currently incomplete.

**Comment by ghost** [comment]
Good to know! Thanks for the link! It seems the feature I want is not implemented, but this documentation will prove useful, regardless.
