### ISSUE TITLE
Bug: It is impossible to purchase Doodles. (Intentional?)

### ISSUE THREAD

**Issue by thehopja** [open-toontown/open-toontown#33]
As it says on the tin. If you go to the Pet Shop and try to talk to the Pet Shop Clerk, the game will softlock after the camera transition to the Clerk since the GUI doesn't show up. I am sure this is likely intentional due to Doodles not being coded in, but wouldn't it make more sense to disable the Clerks like how the Fishermen are disabled?

**Comment by ooowoothevirtualhowler** [comment]
This is because the list of pets is generated and returned by PetManagerAI. Currently PetManagerAI is just a stub right now.
