### ISSUE TITLE
How to implement Magic Words?

### ISSUE THREAD

**Issue by danr789** [open-toontown/open-toontown#36]
Tried to copy the File to "toontown" directory, but still it does not work. The README.md says to add it to the astrondb 'dclass' file, but the file is not located. So can someone explain how to get it implemented and how to max your toon.

**Comment by MrCheeze446** [comment]
there already are magic words, like 4 of them

https://github.com/open-toontown/open-toontown/blob/develop/toontown/spellbook/MagicWordIndex.py
