### ISSUE TITLE
Game Gives "No Districts are available. Try Again?" Even when ai is finished loading.

### ISSUE THREAD

**Issue by 2Epik4u** [open-toontown/open-toontown#46]
When you click ok it loads the game fine. just wanted to address that issue

**Comment by danr789** [comment]
Looks Like I found the same error
` File "C:\Users\admin\Downloads\Toontown Unity\PANDA 3D Toowntown Stuff\open-toontown-develop\toontown\building\DistributedToonInteriorAI.py", line 44, in getSavedBy
    for avId, name, dnaTuple in self.building.savedBy:
TypeError: 'NoneType' object is not iterable`

This is from the AI server, keeps restarting.

Delete the buildings.json files ( all of them ) and restart to see if it works.

**Comment by 2Epik4u** [comment]
no that error was fixed recently in this commit  5f79392 you need to pull
