### ISSUE TITLE
Flippy is in the wrong place

### ISSUE THREAD

**Issue by parallelkneecaps** [open-toontown/open-toontown#50]
![toontown-screenshot-Wed-Sep-15-18-58-10-2021-46575](https://user-images.githubusercontent.com/90913418/133789495-815a06ba-9d6f-4c24-b8a8-440e7a292709.jpg)
And i can't find dimm either... it says his nametag is where flippy is

**Comment by opentoontown** [comment]
fixed as of https://github.com/open-toontown/open-toontown/commit/61a044e2e0d20eacc9bf959255657a2e18c22d3a

dimm & the other NPCs are hidden by default, so this is normal behavior.
