### ISSUE TITLE
Will disabled minigames be able to be toggled on or off?

### ISSUE THREAD

**Issue by ghost** [open-toontown/open-toontown#7]
In the final years of Toontown Online, both Photo Fun, and Trolley Tracks were disabled for unclear reasons.

Looking at the code, the assets, and code to make these work is still present, but goes unused. 

Seeing as you updated code for both Photo Fun, and Trolley Tracks, does this mean the minigames will be in Open Toontown, and how will they be added in (maybe a toggle server wise to enable or disable them?)

**Comment by jwcotejr** [comment]
Yes.

Photo Fun is already enabled, as the `want-all-minigames` config variable currently resolves to `True`, but this can be overridden in `Configrc.prc` if desired.

Trolley Tracks will rely on the holidays for it being implemented, which will likely happen at some point in the future.

**Comment by ghost** [comment]
Ah, that's how it all works, gotcha. 

Thanks for clarifying! Wasn't quite sure how this would all work out at first, but now i get it.
