### ISSUE TITLE
Running into issues when running on Ubuntu

### ISSUE THREAD

**Issue by zenith110** [open-toontown/open-toontown#80]
Howdy!

Want to say a great project y'all are doing. 

I gotten the 3 main scripts for Ubuntu running, and built a release version of Astron. 

However, when starting the game, uberdog quits when trying to log in the client. 

The error that occurs is name File "open-toontown/otp/login/AstronLoginManagerUD.py", line 223, in __handleSetAccount
    self.loginManager.air.ourChannel, CLIENTAGENT_EJECT)' CLIENTAGENT_EJECT not defined"

Doing some research it looks like this correlates to an issue with Astron connection, I have a sole Astron release  binary that was compiled so unsure if there should be other files or if a debugging binary should be compiled instead. 

I'm not sure why it jumps immediately to ejecting as uberdog doesn't show any errors before then, and Astron mentions that the connection was lost due to end of file.

Appreciate all the help!

**Comment by DarthMDev** [comment]
Did you install the custom build of panda3d?

**Comment by zenith110** [comment]
Yes, I compiled the custom fork the repository suggest again to double check and it still has the same error.

**Comment by opentoontown** [comment]
Hi there,

My apologies; this was my bad. This should be resolved in the latest commit.

Take care

**Comment by zenith110** [comment]
That did it, thank you all! :)
